on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    name: dev
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install

      - name: run tests
        run: bun vitest

      - name: apply migration
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          bun wrangler d1 migrations apply DB --remote

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_SECRET: ${{ secrets.BOT_SECRET }}
          BOT_DEVELOPER: ${{ secrets.BOT_DEVELOPER }}
          KEY: ${{ secrets.KEY }}
          IV: ${{ secrets.IV }}
          PROXY: ${{ secrets.PROXY }}
          PROXY_SIGNATURE: ${{ secrets.PROXY_SIGNATURE }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          INSTITUTE_ID: ${{ secrets.INSTITUTE_ID }}
          LIMIT_PER_DAY: ${{ secrets.LIMIT_PER_DAY }}
